# path to database sheet (TSV format, columns: database_name, path_db)
databases: config/databases.tsv

# path to contigs folder
contigs: /Users/rdenise/Documents/script/virome_pipeline/myfiles/contigs

contigs_ext: fasta.gz

# name of the project 
project_name: your_project_name

# path to the result folder
output_folder: results

# Blast option if not given in seeds.tsv
default_blast_option:
    # E-value threshold
    e_val: 0.0001

# Default value for plot
default_values_plot:
    # Color
    color: '#131516' # This color is a dark grey similar to black
    # Turn color of the border a darker shade infer from the background if True else set the color to black
    colored_border: True
    # Turn border to roundish shape
    round_border: False
