$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  project_name:
    type: string
  output_folder:
    type: string
  databases:
    type: string
  contigs:
    type: string
  contigs_ext:
    type: string

  default_blast_option:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
    required:
      - e_val

  default_values_plot:
    type: object
    properties:
      color:
        type: string
      colored_border:
        type: boolean
      round_border:
        type: boolean
 
  default_prokka_option:
    type: object
    properties:
      protein_db:
        type: string
      hmm_db:
        type: string
      kingdom:
        type: string

required:
  - databases
  - contigs
  - contigs_ext
  - project_name
  - output_folder
  - default_blast_option
  - default_prokka_option
  