$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  project_name:
    type: string
  output_folder:
    type: string

  databases:
    type: string
  contigs:
    type: string
      
  default_blast_option:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
    required:
      - e_val

  default_values_plot:
    type: object
    properties:
      color:
        type: string
      colored_border:
        type: boolean
      round_border:
        type: boolean

required:
  - databases
  - contigs
  - project_name
  - output_folder
  - default_psiblast_option